/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as SignupPendingRouteImport } from './routes/signup.pending'
import { Route as BusinessWalletRouteImport } from './routes/business.wallet'
import { Route as BusinessSupportRouteImport } from './routes/business.support'
import { Route as BusinessRequestsRouteImport } from './routes/business.requests'
import { Route as BusinessProfileRouteImport } from './routes/business.profile'
import { Route as BusinessNewRequestRouteImport } from './routes/business.new-request'
import { Route as BusinessRequestsIdRouteImport } from './routes/business.requests.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const SignupPendingRoute = SignupPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => SignupRoute,
} as any)
const BusinessWalletRoute = BusinessWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSupportRoute = BusinessSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessRequestsRoute = BusinessRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessNewRequestRoute = BusinessNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessRequestsIdRoute = BusinessRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRouteWithChildren
  '/business/new-request': typeof BusinessNewRequestRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/requests': typeof BusinessRequestsRouteWithChildren
  '/business/support': typeof BusinessSupportRoute
  '/business/wallet': typeof BusinessWalletRoute
  '/signup/pending': typeof SignupPendingRoute
  '/business/': typeof BusinessIndexRoute
  '/business/requests/$id': typeof BusinessRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRouteWithChildren
  '/business/new-request': typeof BusinessNewRequestRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/requests': typeof BusinessRequestsRouteWithChildren
  '/business/support': typeof BusinessSupportRoute
  '/business/wallet': typeof BusinessWalletRoute
  '/signup/pending': typeof SignupPendingRoute
  '/business': typeof BusinessIndexRoute
  '/business/requests/$id': typeof BusinessRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRouteWithChildren
  '/business/new-request': typeof BusinessNewRequestRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/requests': typeof BusinessRequestsRouteWithChildren
  '/business/support': typeof BusinessSupportRoute
  '/business/wallet': typeof BusinessWalletRoute
  '/signup/pending': typeof SignupPendingRoute
  '/business/': typeof BusinessIndexRoute
  '/business/requests/$id': typeof BusinessRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/signin'
    | '/signup'
    | '/business/new-request'
    | '/business/profile'
    | '/business/requests'
    | '/business/support'
    | '/business/wallet'
    | '/signup/pending'
    | '/business/'
    | '/business/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/business/new-request'
    | '/business/profile'
    | '/business/requests'
    | '/business/support'
    | '/business/wallet'
    | '/signup/pending'
    | '/business'
    | '/business/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/signin'
    | '/signup'
    | '/business/new-request'
    | '/business/profile'
    | '/business/requests'
    | '/business/support'
    | '/business/wallet'
    | '/signup/pending'
    | '/business/'
    | '/business/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/signup/pending': {
      id: '/signup/pending'
      path: '/pending'
      fullPath: '/signup/pending'
      preLoaderRoute: typeof SignupPendingRouteImport
      parentRoute: typeof SignupRoute
    }
    '/business/wallet': {
      id: '/business/wallet'
      path: '/wallet'
      fullPath: '/business/wallet'
      preLoaderRoute: typeof BusinessWalletRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/support': {
      id: '/business/support'
      path: '/support'
      fullPath: '/business/support'
      preLoaderRoute: typeof BusinessSupportRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/requests': {
      id: '/business/requests'
      path: '/requests'
      fullPath: '/business/requests'
      preLoaderRoute: typeof BusinessRequestsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/profile': {
      id: '/business/profile'
      path: '/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/new-request': {
      id: '/business/new-request'
      path: '/new-request'
      fullPath: '/business/new-request'
      preLoaderRoute: typeof BusinessNewRequestRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/requests/$id': {
      id: '/business/requests/$id'
      path: '/$id'
      fullPath: '/business/requests/$id'
      preLoaderRoute: typeof BusinessRequestsIdRouteImport
      parentRoute: typeof BusinessRequestsRoute
    }
  }
}

interface BusinessRequestsRouteChildren {
  BusinessRequestsIdRoute: typeof BusinessRequestsIdRoute
}

const BusinessRequestsRouteChildren: BusinessRequestsRouteChildren = {
  BusinessRequestsIdRoute: BusinessRequestsIdRoute,
}

const BusinessRequestsRouteWithChildren =
  BusinessRequestsRoute._addFileChildren(BusinessRequestsRouteChildren)

interface BusinessRouteChildren {
  BusinessNewRequestRoute: typeof BusinessNewRequestRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  BusinessRequestsRoute: typeof BusinessRequestsRouteWithChildren
  BusinessSupportRoute: typeof BusinessSupportRoute
  BusinessWalletRoute: typeof BusinessWalletRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessNewRequestRoute: BusinessNewRequestRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  BusinessRequestsRoute: BusinessRequestsRouteWithChildren,
  BusinessSupportRoute: BusinessSupportRoute,
  BusinessWalletRoute: BusinessWalletRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface SignupRouteChildren {
  SignupPendingRoute: typeof SignupPendingRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupPendingRoute: SignupPendingRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
